server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

# MySQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
# amqp
  rabbitmq:
    host: 47.92.228.54
    port: 5672
    username: shengzeznkj
    password: szznkj

# mqtt
com:
  mqtt:
    host: 47.92.228.54
    port: 1883
    username: shengzeznkj
    password: szznkj
    timeout: 60
    keepAlive: 180
    preFix: 'tcp://'

shadow:
  auto-init: true

